// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyASgo6LwP8TdEfXeKoWsStlBg6zd0mZTEk',
//     appId: '1:1099331486837:web:b3a68c79c01c4f5f6fe43c',
//     messagingSenderId: '1099331486837',
//     projectId: 'gestioncertificat-ce8fc',
//     authDomain: 'gestioncertificat-ce8fc.firebaseapp.com',
//     storageBucket: 'gestioncertificat-ce8fc.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBUS9N2X4lq91oZUACEr_-u96kzxLBeYPA',
//     appId: '1:1099331486837:android:528e1ece99aff2fc6fe43c',
//     messagingSenderId: '1099331486837',
//     projectId: 'gestioncertificat-ce8fc',
//     storageBucket: 'gestioncertificat-ce8fc.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBJVEsacBtVwkfI14fySQuW8YVIYgP5ESo',
//     appId: '1:1099331486837:ios:b60ca3313e8f52ec6fe43c',
//     messagingSenderId: '1099331486837',
//     projectId: 'gestioncertificat-ce8fc',
//     storageBucket: 'gestioncertificat-ce8fc.firebasestorage.app',
//     iosBundleId: 'com.example.gestionCertificat',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBJVEsacBtVwkfI14fySQuW8YVIYgP5ESo',
//     appId: '1:1099331486837:ios:b60ca3313e8f52ec6fe43c',
//     messagingSenderId: '1099331486837',
//     projectId: 'gestioncertificat-ce8fc',
//     storageBucket: 'gestioncertificat-ce8fc.firebasestorage.app',
//     iosBundleId: 'com.example.gestionCertificat',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyASgo6LwP8TdEfXeKoWsStlBg6zd0mZTEk',
//     appId: '1:1099331486837:web:a70ff9957560c7516fe43c',
//     messagingSenderId: '1099331486837',
//     projectId: 'gestioncertificat-ce8fc',
//     authDomain: 'gestioncertificat-ce8fc.firebaseapp.com',
//     storageBucket: 'gestioncertificat-ce8fc.firebasestorage.app',
//   );
// }
