// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5WhREJZF6rpZu9cu4ozt-i4JGcUDBM7I',
    appId: '1:223318233035:web:cd550118f785c31e59b04e',
    messagingSenderId: '223318233035',
    projectId: 'gestion-4dda7',
    authDomain: 'gestion-4dda7.firebaseapp.com',
    storageBucket: 'gestion-4dda7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPA8-_I8Lz6sZSmZAgJur98eX-DSC_F_s',
    appId: '1:223318233035:android:e97bc27bfcbccaf359b04e',
    messagingSenderId: '223318233035',
    projectId: 'gestion-4dda7',
    storageBucket: 'gestion-4dda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoLmw-M4gaO6soYH7eKO5w4wYCNNBy6YE',
    appId: '1:223318233035:ios:5ca66148f3df937959b04e',
    messagingSenderId: '223318233035',
    projectId: 'gestion-4dda7',
    storageBucket: 'gestion-4dda7.firebasestorage.app',
    iosBundleId: 'com.example.gestionCertificat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoLmw-M4gaO6soYH7eKO5w4wYCNNBy6YE',
    appId: '1:223318233035:ios:5ca66148f3df937959b04e',
    messagingSenderId: '223318233035',
    projectId: 'gestion-4dda7',
    storageBucket: 'gestion-4dda7.firebasestorage.app',
    iosBundleId: 'com.example.gestionCertificat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5WhREJZF6rpZu9cu4ozt-i4JGcUDBM7I',
    appId: '1:223318233035:web:b397b599f2a9660e59b04e',
    messagingSenderId: '223318233035',
    projectId: 'gestion-4dda7',
    authDomain: 'gestion-4dda7.firebaseapp.com',
    storageBucket: 'gestion-4dda7.firebasestorage.app',
  );
}
